---
- name: Install Packages on the laptop
  hosts: localhost

  vars_files: mypackages.yml
  
  tasks:
    - name: Ensure Visual Studio Code Repo is set up
      yum_repository:
        name: vscode
        description: "Visual Studio Code"
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        enabled: true
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
      tags:
        - repo

    - name: Ensure DNF cache is up to date
      dnf:
        name: '*'
        state: latest
      tags:
        - repo

    - name: Install All Packages
      dnf:
        name: "{{ item.name }}"
        state: present
      loop: "{{ packages }}"
      tags:
        - install

