---
- name: Install Packages on the laptop
  hosts: localhost

  vars_files: mypackages.yml
  
  tasks:
    - name: Ensure Visual Studio Code Repo is set up
      yum_repository:
        name: vscode
        description: "Visual Studio Code"
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        enabled: true
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
      tags:
        - repo

    - name: Ensure DNF cache is up to date
      dnf:
        name: '*'
        state: latest
      tags:
        - repo

    - name: Download msttcorefonts package
      get_url:
        url: "{{ msttfonts_url }}"
        dest: "{{ msttfonts_rpm }}"
      register: msttfonts_result
      tags:
        - repo

    - name: Install MS TrueType Fonts
      dnf:
        name: "{{ item.name }}"
        state: present
        disable_gpg_check: true
      loop: "{{ msttfont_packages }}"
      tags:
        - repo

    - name: Install All Packages
      dnf:
        name: "{{ item.name }}"
        state: present
      loop: "{{ packages }}"
      tags:
        - install

    - name: configure avahi
      service:
        name: avahi-daemon
        state: started
        enabled: true
      tags:
        - configure

    - name: Ensure nsswitch config is set correctly for avahi
      lineinfile:
        path: /etc/authselect/user-nsswitch.conf
        regexp: '^hosts:      files mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] myhostname dns'
        line: 'hosts: files mdns4_minimal [NOTFOUND=return] dns myhostname'
      notify:
        - restart avahi
      tags:
        - configure
    
    - name: Apply nsswitch changes
      command: 'authselect apply-changes'
      tags:
        - configure
    
    - name: Ensure user is in libvirt group
      user:
        name: smeeuwsen
        groups: wheel,libvirt
      tags:
        - configure

    - name: Removing temp packages
      file:
        path: "{{ msttfonts_rpm }}"
        state: absent
      when: msttfonts_result.failed == false
      tags:
        - repo

  handlers:
    - name: restart avahi
      service:
        name: avahi-daemon
        state: restarted